Add tr() descriptors for Taproot output scripts
bitcoin-core/HWI pull request #545
Opened 2021-11-19 17:52 UTC by achow101

Implements `tr()` descriptors

2021-11-19 17:58 UTC, prusnak requested changes

2021-11-19 17:58 UTC, prusnak commented on hwilib/descriptor.py
> +    Descriptors can contain multiple :class:`PubkeyProvider`\ s and multipe ``Descriptor`` as subdescriptors.
```suggestion
    Descriptors can contain multiple :class:`PubkeyProvider`\ s and multiple ``Descriptor`` as subdescriptors.
```

2021-11-19 18:07 UTC, achow101 commented on hwilib/descriptor.py
> +    Descriptors can contain multiple :class:`PubkeyProvider`\ s and multipe ``Descriptor`` as subdescriptors.
Done

2021-12-06 04:00 UTC, Sjors reviewed
6dedec4c2f8374fb93501152ae3aa327ec61084b looks alright, but I did not study the merkle tree parsing and writing code much.

You could add some more test vectors (from Bitcoin Core?), which are needed for https://github.com/bitcoin/bips/blob/master/bip-0386.mediawiki anyway.

2021-12-06 21:18 UTC, achow101 commented on hwilib/descriptor.py
> -    if func == "pkh":
Done

2021-12-09 12:43 UTC, Sjors commented
Thanks for the changes in 6539d6c4967f74fa2a2bcc022067d3c9dd3cb9c2. I still think more test vectors would be useful here.

2021-12-10 16:33 UTC, achow101 commented
Core doesn't really have any test vectors that we can use.

2021-12-13 13:53 UTC, prusnak commented
> Core doesn't really have any test vectors that we can use.

Feel free to use the test vectors from:
* https://github.com/satoshilabs/slips/blob/master/slip-0014.md#bitcoin-taproot--p2tr--bip86
* https://github.com/satoshilabs/slips/blob/master/slip-0014.md#bitcoin-testnet-taproot--p2tr--bip86

2021-12-15 08:26 UTC, Sjors commented
utACK d2d360c4cc7db84afea41c56497cf33f0726b136

2021-12-15 19:33 UTC, merged