trezor: restore support for external inputs
bitcoin-core/HWI pull request #590
Opened 2022-03-17 14:58 UTC by matejcik

partially reverts #581 

implements unverified external inputs for Trezor, per https://github.com/trezor/trezor-firmware/blob/master/docs/common/communication/bitcoin-signing.md#external-inputs

Unit tests are passing for me locally, except big_tx in the newly added test suite, but that's bitcoincore complaining that "This wallet has no available keys (-4)". I have no idea what to do about that -- maybe something went wrong because of the way I subclass?

2022-03-23 10:54 UTC, matejcik commented
Fixed big_tx failure by extending the size of the keypool. I am still not entirely sure why it carries over between test runs but :woman_shrugging: 

Also added support for forwarding signature data to Trezor if available. This enables Trezor T "verified external input" mode. Adding support for SLIP-19 ownership proofs would be simple, assuming they are either (a) added to BIP-174 or (b) SLIP-19 is changed to use a vendor prefix.

2022-05-18 19:16 UTC, prusnak commented
I thought lots of people use HWI to sign mixed environment transactions that bring external inputs into the mix, no?

2022-05-18 19:22 UTC, achow101 commented
> I thought lots of people use HWI to sign mixed environment transactions that bring external inputs into the mix, no?

No idea. No one's complained about the latest release which includes #581.

2022-05-18 22:01 UTC, prusnak requested changes
Left couple of nits when it comes to versioning.

2022-05-18 22:01 UTC, prusnak commented on hwilib/devices/trezor.py
> +    if client.features.model == "1" and client.version > (1, 10, 5):
This is better and matches more how people think:
```suggestion
    if client.features.model == "1" and client.version >= (1, 11, 1):
```

2022-05-18 22:01 UTC, prusnak commented on hwilib/devices/trezor.py
> +    if client.features.model == "T" and client.version > (2, 4, 3):
This is better and matches more how people think:
```suggestion
    if client.features.model == "T" and client.version > (2, 5, 1):
```

2022-06-01 17:03 UTC, elkimek commented
@achow101 I think it's the other way around. No one uses external inputs because no one implemented it as an useful tool.

Sparrow Wallet recently implemented privacy enhancing features such as Stonewall 2x (two party CoinJoin) and Stowaway (PayJoin) which people actually use on daily basis. With Trezor's external inputs it would be possible to do that from hardware wallets which in my opinion would close the gap where users needs to choose between security and privacy tradeoffs.

See https://github.com/sparrowwallet/sparrow/issues/368

2024-01-17 19:06 UTC, achow101 commented
Is this still relevant?

2024-01-17 19:33 UTC, prusnak commented
I think so. Can you please confirm @matejcik?

2024-01-18 10:10 UTC, matejcik commented
I will need to update the PR in light of #713 but otherwise yes, this is still desired.

2024-07-01 13:36 UTC, matejcik commented
PR updated and pointed on top of #742

2026-08-18 18:06 UTC, achow101 commented
Closing as part of sunsetting described in #850

2026-08-18 18:06 UTC, closed without merging