bitbox02: add taproot support to display_singlesig_address
bitcoin-core/HWI pull request #611
Opened 2022-06-08 08:48 UTC by Beerosagos

2022-06-08 08:52 UTC, prusnak requested changes

2022-06-08 08:52 UTC, prusnak commented on hwilib/devices/bitbox02.py
> +        mrs += "m/86'/0'/<account'> for p2tr;"
most probably a typo?
```suggestion
        msg += "m/86'/0'/<account'> for p2tr;"
```

2022-06-14 09:06 UTC, benma commented
This is ready to merge. cc @achow101

2022-06-14 22:04 UTC, achow101 commented
ACK 90a1c2320c210dbe1fb479f7db131942c32875aa

2022-06-14 22:04 UTC, merged