feat(devices): add onekey support
bitcoin-core/HWI pull request #672
Opened 2023-03-27 02:15 UTC by somebodyLi

2023-07-19 22:37 UTC, achow101 commented
Is there a simulator/emulator for the onekey? Can you add tests so that CI can check against it? See https://github.com/bitcoin-core/HWI/blob/master/test/test_trezor.py and https://github.com/bitcoin-core/HWI/blob/master/test/test_keepkey.py for examples of how to do that.

2023-07-20 02:26 UTC, 424778940z commented
Sure, we working on it.

2023-07-26 09:52 UTC, prusnak requested changes
I requested some changes below, so your newly added code does not get triggered when a Trezor is connected.

Please connect a Trezor and test whether HWI still works correctly (and Trezor code path is used for communicating with Trezor, not Onekey code path).

2023-07-26 09:52 UTC, prusnak commented on hwilib/devices/onekey.py
> +VENDORS = ("onekey.so", "trezor.io",)
Fix:

```suggestion
VENDORS = ("onekey.so", )
```

2023-07-26 09:52 UTC, prusnak commented on hwilib/devices/onekey.py
> +USB_IDS = {(0x1209, 0x4F4A), (0x1209, 0x4F4B), (0x1209, 0x53C1)}
Fix:

```suggestion
USB_IDS = {(0x1209, 0x4F4A), (0x1209, 0x4F4B), }
```

2023-07-26 09:52 UTC, prusnak commented on hwilib/udev/51-onekey.rules
> +SUBSYSTEM=="usb", ATTR{idVendor}=="1209", ATTR{idProduct}=="53c1", MODE="0660", GROUP="plugdev", TAG+="uaccess", TAG+="udev-acl", SYMLINK+="onekey%n"
This is a Trezor USB ID, don't include it here:
```suggestion
```

2023-08-31 06:13 UTC, closed without merging